name: Publish Docker image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: docker login
          env:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
          run: docker login -u $username -p $password
      - name: docker build
        run: docker build ./src -t mdevos/besturingssystemen2:latest
      - name: docker push
        run: docker push mdevos/besturingssystemen2:latest
