name: Java CI

on:
  push:
    branches: [master]

jobs:
  maven:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mdevos5/besturingssystemen2
          tags: latest
          tag_with_ref: true

  release:
    runs-on: ubuntu-latest
    steps:
    - name: Build & test
      run: |
              echo "done!"
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: Development Build
          #files: |
          #      LICENSE.txt
          #      *.jar


      #- name: Check out the repo
      #  uses: actions/checkout@v2
      #- name: docker login
      #  run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      #- name: docker build
      #  run: docker build -t besturingssystemen2 .
      #- name: tag image
      #  run: docker tag besturingssystemen2 mdevos5/besturingssystemen2
      #- name: docker push
      #  run: docker push mdevos5/besturingssystemen2
